### ISSUE TITLE
"Open in master" should be replaced with "open in main"

### ISSUE THREAD

**Issue by ComputerDruid** [j-wing/fuchsia-git-helper#10]
When I use this extension to grab a link I always have to manually replace the master part of the URL with main before sharing. It would be slightly more convenient if it did that automatically.

I'd be happy to contribute a fix for this, but I currently can't because of #9

**Comment by ComputerDruid** [comment]
Extra note: even with this inconvenience, the extension is still really convenient, so thanks for writing it!

**Comment by j-wing** [comment]
Now that the license is in, if you have a chance to put up a PR for this I'd be happy to review!
