### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ComputerDruid** [j-wing/fuchsia-git-helper#9]
I couldn't find any license info for this repository. If you could clarify what license the code is under, that would let me contribute to it (assuming it's under a reasonable license)

**Comment by j-wing** [comment]
Hi there, I don't have a strong opinion on the license! Apache is what I used for a different project while I was at Google - would that compatible with your contributing?

**Comment by ComputerDruid** [comment]
Sure, Apache2 is fine for me. Or another sensible choice would be picking the same license as most fuchsia code uses: https://cs.opensource.google/fuchsia/fuchsia/+/main:LICENSE , which I believe is https://opensource.org/licenses/BSD-2-Clause

**Comment by j-wing** [comment]
I like that idea - I just added the BSD-2 clause license to `main`.
